---
- name: Copy from kvm-a00c source to all remote guests (linux)
  hosts: linux
  become: yes
  tasks:
    - name: Copy /etc/hosts file
      copy:
        src: /etc/hosts
        dest: /etc/hosts
        backup: yes

- name: Copy from kvm-a00c source to all remote guests (windows)
  hosts: windows
  tasks:
    - name: Copy /etc/hosts file
      ansible.windows.win_copy:
        src: /etc/hosts
        dest: C:\Windows\System32\drivers\etc\hosts
        backup: yes
