---
- hosts: centos debian ubuntu suse templates
  tasks:
    #  - name: Install software
    #    ansible.builtin.package:
    #      name:
    #        - cockpit
    #      state: latest
    #  - name: start cockpit
    #    systemd:
    #      name: cockpit
    #      state: started
    #  - name: enable cockpit.socket
    #    systemd:
    #      name: cockpit.socket
    #      enabled: yes
  - name: Firewall rules
    firewalld:
      service: zabbix
      permanent: true
      state: enabled
      immediate: yes
