---
- name: Change user passwords on Linux
  hosts: linux
  vars_files:
    - group_vars/linux/vault.yml

  tasks:
    - name: Change virtual user password
      ansible.builtin.user:
        name: virtual
        state: present
        password: "{{ linux_virtual_password }}"

    - name: Change sshsvusr user password
      ansible.builtin.user:
        name: sshsvusr
        state: present
        password: "{{ linux_sshsvusr_password }}"

    - name: Change root user password
      ansible.builtin.user:
        name: root
        state: present
        password: "{{ linux_root_password }}"

#ansible-vault create group_vars/linux/vault.yml

## group_vars/linux/vault.yml
#linux_virtual_password: 'P@ssw0rd!'
#linux_root_password: 'P@ssw0rd!'
#linux_sshsvusr_password: 'P@ssw0rd!'
