---
- name: System Resource Information (Using Ansible Facts)
  hosts: all
  gather_facts: yes
  tasks:
    - name: Get mounted filesystem information
      setup:
        filter: ansible_mounts

    - name: Display disk usage information
      debug:
        msg: |
          Partition: {{ item.mount }}
          Device: {{ item.device }}
          Filesystem: {{ item.fstype }}
          Size: {{ (item.size_total / 1024 / 1024 / 1024) | round(2) }} GB
          Used: {{ ((item.size_total - item.size_available) / 1024 / 1024 / 1024) | round(2) }} GB
          Available: {{ (item.size_available / 1024 / 1024 / 1024) | round(2) }} GB
          Usage: {{ (((item.size_total - item.size_available) / item.size_total) * 100) | round(1) }}%
          ---
      loop: "{{ ansible_mounts }}"
      when: item.size_total is defined

    - name: Display memory information
      debug:
        msg: |
          Total Memory: {{ (ansible_memtotal_mb / 1024) | round(2) }} GB
          Free Memory: {{ (ansible_memfree_mb / 1024) | round(2) }} GB
          Used Memory: {{ ((ansible_memtotal_mb - ansible_memfree_mb) / 1024) | round(2) }} GB
          Memory Usage: {{ (((ansible_memtotal_mb - ansible_memfree_mb) / ansible_memtotal_mb) * 100) | round(1) }}%

    - name: Get current CPU load
      shell: cat /proc/loadavg
      register: load_avg
      changed_when: false

    - name: Display CPU load information
      debug:
        msg: |
          CPU Load Average: {{ load_avg.stdout }}
          CPU Cores: {{ ansible_processor_vcpus }}
          Load per core: {{ (load_avg.stdout.split()[0] | float / ansible_processor_vcpus) | round(2) }}
