---
- name: Change user passwords on Windows
  hosts: windows
  vars_files:
    - group_vars/windows/vault.yml

  tasks:
    - name: Change virtual user password
      ansible.windows.win_user:
        name: virtual
        state: present
        password: "{{ windows_virtual_password }}"

    - name: Change sshsvusr user password
      ansible.windows.win_user:
        name: sshsvusr
        state: present
        password: "{{ windows_sshsvusr_password }}"

    - name: Change Administrator user password
      ansible.windows.win_user:
        name: Administrator
        state: present
        password: "{{ windows_admin_password }}"

#ansible-vault create group_vars/windows/vault.yml

## group_vars/windows/vault.yml
#windows_virtual_password: 'P@ssw0rd!'
#windows_admin_password: 'P@ssw0rd!'
#windows_sshsvusr_password: 'P@ssw0rd!'
